apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-synapse"
spec:
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      serviceAccountName: "{{ .Release.Name }}-synapse"
      containers:
        - name: synapse
          image: "{{ .Values.synapse.image }}"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: POSTGRES
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-database-credentials"
                  key: superuser
            - name: IN_CLUSTER
              value: "true"
          resources:
            limits:
              memory: 72M
            requests:
              memory: 72M
