apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-oauthproxy"
spec:
  selector:
    matchLabels:
      app: oauthproxy
  template:
    metadata:
      labels:
        app: oauthproxy
    spec:
      containers:
        - name: oauthproxy
          image: "{{ .Values.oauthproxy.image }}"
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: ACCEPTED_DOMAIN
              value: "{{ .Values.domain }}"
