apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-gateway"
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: asyncy/http:v0.2.1-33-g536a1cb
          args:
            - python
            - -m
            - app.main
            - --logging=debug
            - --debug
          ports:
            - name: public
              containerPort: 8888
            - name: internal
              containerPort: 8889
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-gateway-config"
                  key: sentry-dsn
          resources:
            limits:
              memory: 64M
            requests:
              memory: 64M
