apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-graphql"
  labels:
    app: graphql
spec:
  {{- if .Values.tls.enabled -}}
  tls:
  - hosts:
     - "api.{{ .Values.domain }}"
    secretName: "{{ .Release.Name }}-tls-cert"
  {{ end }}
  rules:
  - host: "api.{{ .Values.domain }}"
    http:
      paths:
      - path: /graphql
        backend:
          serviceName: "{{ .Release.Name }}-graphql"
          servicePort: 3000
      - path: /graphiql
        backend:
          serviceName: "{{ .Release.Name }}-graphql"
          servicePort: 3000
      - path: /_postgraphile
        backend:
          serviceName: "{{ .Release.Name }}-graphql"
          servicePort: 3000
