apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-sls"
  labels:
    app: sls
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  {{- if .Values.tls.enabled -}}
  tls:
  - hosts:
     - "sls.{{ .Values.domain }}"
    secretName: "{{ .Release.Name }}-tls-cert"
  {{ end }}
  rules:
  - host: "sls.{{ .Values.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-sls"
          servicePort: 2042
