apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-auth"
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: {{ include "storyscript.image" .Values.auth.image }}
          ports:
            - name: public
              containerPort: 3000
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-database-credentials"
                  key: superuser-search_path
            - name: SSL_MODE
              value: "disable"
            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-auth"
                  key: jwt_secret_key
            - name: GH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-auth"
                  key: github_client_id
            - name: GH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-auth"
                  key: github_client_secret
            - name: DOMAIN
              value: "{{ .Values.domain }}"
            - name: SELF_DOMAIN
              value: http{{ ternary "s" "" .Values.tls.enabled }}://auth.{{ .Values.domain }}
            - name: DEFAULT_REDIRECT_URI
              value: http{{ ternary "s" "" .Values.tls.enabled }}://{{ .Values.domain }}
            - name: ALLOWLIST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-auth"
                  key: allowlist_token
